<?php
$HOSTNAME = "localhost";//SERVIDOR
$USERNAME = "daniel";		//USUARIO
$PASSWORD = "daniel";		//CONTRASEÑA
$DATABASE = "noticias";	//BASE DE DATOS
$NRPP=7; // NUMERO DE REGISTROS POR PAGINA DEL PAGINADOR.
?>